# Generated by Django 3.1.7 on 2021-03-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contact_info',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
